image: Visual Studio 2019

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'

platform: Any CPU
configuration: Release

build:
  verbosity: normal